### ISSUE TITLE
Got error while running 248-stable-diffusion-xl

### ISSUE THREAD

**Issue by tarunmcom** [openvinotoolkit/openvino_notebooks#1247]
**I am running on Serpent Canyon which has arc 770 GPU. I got this error:-**  

Compiling the vae_decoder...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 5
      3     text2image_pipe.half()
      4     text2image_pipe.save_pretrained(model_dir)
----> 5     text2image_pipe.compile()
      6 else:
      7     text2image_pipe = OVStableDiffusionXLPipeline.from_pretrained(model_dir, device=device.value)

File ~\anaconda3\envs\sdxl\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py:487, in OVStableDiffusionPipelineBase.compile(self)
    486 def compile(self):
--> 487     self.vae_decoder._compile()
    488     self.unet._compile()
    489     for component in {self.text_encoder, self.text_encoder_2, self.vae_encoder}:

File ~\anaconda3\envs\sdxl\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py:533, in OVModelPart._compile(self)
    531 if self.request is None:
    532     logger.info(f"Compiling the {self._model_name}...")
--> 533     self.request = core.compile_model(self.model, self.device, self.ov_config)

File ~\anaconda3\envs\sdxl\lib\site-packages\openvino\runtime\ie_api.py:543, in Core.compile_model(self, model, device_name, config)
    537 if device_name is None:
    538     return CompiledModel(
    539         super().compile_model(model, {} if config is None else config),
    540     )
    542 return CompiledModel(
--> 543     super().compile_model(model, device_name, {} if config is None else config),
    544 )

RuntimeError: Exception from src\inference\src\core.cpp:118:
[ GENERAL_ERROR ] Check 'false' failed at src\plugins\intel_gpu\src\plugin\program.cpp:401:
GPU program build failed!
Exception from src\plugins\intel_gpu\src\graph\include\primitive_type_base.h:58:
[GPU] Can't choose implementation for constant:Reshape_261408_reorder_convolution:/decoder/up_blocks.0/resnets.2/conv2/Conv/WithoutBiases node (type=reorder)
[GPU] Original name: 
[GPU] Original type: 
[GPU] Reason: vector too long

**Comment by Aznie-Intel** [comment]
Hi @tarunmcom, I also observed a similar issue when running the notebook.

![stable](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156850/1af6863e-afb2-4493-b2cb-7c9dda144ff6)
![stable 2](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156850/ccf8b4a8-a9d4-4822-9603-4c35c4a39770)

I will highlight the issues with the relevant team and update here soon.

**Comment by avitial** [comment]
@tarunmcom I see different errors when executing on iGPU vs dGPU (Arc A770 16GB), sometimes the kernel gets shutdown due to system being out of Memory (my system only has 16GB of RAM), and I also observed a `[ GENERAL_ERROR ] get_shape was called on a descriptor::Tensor with dynamic shape` error when compiling the vae_encoder. FYI we've shared this with the development team, as soon as we have any updates to share we will let you know. 


Ref. 118872

**Comment by avitial** [comment]
@tarunmcom there are two issues that needed to be addressed, the first one is that some of the demonstrated models in this notebook can require at least 64GB RAM for conversion and running. Please ensure your system has enough memory, otherwise the Linux kernel may kill the notebook as it consumes large amounts of memory.

For the second issue faced, openvino==2023.1.0.dev20230811 has a fix for _get_shape() dynamic shape runtime error_.
Please try the latest notebook (commit e31ac564d64c25094601c5b5297d1434d2c59942) with clean python environment. The clean python environment can get the latest optimum version. Then all the outputs with GPU.1 (Arc A770) are good and functional. Let us know if you have any additional questions or if the issue persists, hope this helps.

**Comment by avitial** [comment]
Closing this as issue has been addressed. Feel free to reopen if you have any additional questions or if the issue persists.
