### ISSUE TITLE
227-whisper-subtitles-generation.ipynb not working on ARC GPU

### ISSUE THREAD

**Issue by tarunmcom** [openvinotoolkit/openvino_notebooks#1248]
I am trying to run the model on Serpent Canyon which has ARC 770 GPU. The python kernel crashes every time when I try to run on the dGPU. However it works on cpu and igpu.
:-
The kernel for whisper/227_whisper_subtitles_generation.ipynb appears to have died. It will restart automatically.

**Comment by YuChern-Intel** [comment]
Hi @tarunmcom Thanks for highlighting the issue. 

I encountered the same issue on my end.

I will highlight the issues with the relevant team and update here soon.

**Comment by avitial** [comment]
@tarunmcom please share your system configuration (i.e. versions of operating system, openvino, openvino_notebooks' commit, python, etc. and HW settings like RAM, CPU 12th Generation Intel® Core™ i7-12700H?, etc.). 

Is your discrete GPU configured properly for [Windows](https://docs.openvino.ai/2023.0/openvino_docs_install_guides_configurations_for_intel_gpu.html#windows)/[Linux](https://docs.openvino.ai/2023.0/openvino_docs_install_guides_configurations_for_intel_gpu.html#linux)? Are you able to run other notebooks with dGPU or infer on your dGPU natively using something like OpenVINO's [benchmark_app](https://docs.openvino.ai/2023.0/openvino_inference_engine_tools_benchmark_tool_README.html)?


I am running the _227-whisper-subtitles-generation_ notebook on GPU.1 (Arc A770 16GB) and runs fine on Ubuntu 22.04 with latest master (commit: 03c0402fe43966b1f2f851deb4b46b7ba8ed8cd4). I changed cells 8 and 9 to use _GPU.1_ instead of _CPU_ and selected _GPU.1_ as device in cell 13. 

I can see the dGPU being utilized on my Linux environment (with _[intel_gpu_top](https://manpages.ubuntu.com/manpages/jammy/man1/intel_gpu_top.1.html)_ utility) while the notebook executes. Execution of cell 21 is almost instant on dGPU so I added a for loop to this call to be able to monitor device utilization.
```
for i in range(30):
    transcription = model.transcribe(audio, beam_size=5, best_of=5, task=task.value)
```

discrete-gpu-utilization:

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/20826577/e1ce83f0-8dd6-40fc-b0b8-e4c659b1db99)

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic, if issue persists kindly share the requested information.
