### ISSUE TITLE
notebook 251 image to image always returns black image

### ISSUE THREAD

**Issue by baselqt** [openvinotoolkit/openvino_notebooks#1252]
notebook 251 image to image always returns black image even with default prompt and image and everything configured correctly. text to image works

**Comment by YuChern-Intel** [comment]
Thanks for highlighting this issue.

The behavior only happens when 'AUTO' (by default) or 'GPU' device is selected.

However, Notebook 251-tiny-sd-image-generation is working fine for text-to-image generation and image-to-image generation when selecting CPU device to run inference.

Change value to 'CPU' in cell [8], under section "Configure Inference Pipeline"

**Comment by baselqt** [comment]
okay thank you!

**Comment by YuChern-Intel** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic, if issue persists kindly share the requested information.

**Comment by eaidova** [comment]
@baselqt this PR should fix issue with black image on GPU https://github.com/openvinotoolkit/openvino_notebooks/pull/1329
you can check if it is still interesting for you
