### ISSUE TITLE
issue when running notebook

### ISSUE THREAD

**Issue by alberxualberxu** [openvinotoolkit/openvino_notebooks#1286]
python version is 3.10.8

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/102842442/36a7b2d4-c8d8-4c40-b441-bced6b7c13bc)

**Comment by YuChern-Intel** [comment]
I've validated that 236-stable-diffusion-v2 Notebook is running well on my side.

Try to install IPython kernel in your Python Virtual Environment by running the following commands:
```
python -m pip install ipykernel
python -m ipykernel install --user
```

**Comment by alberxualberxu** [comment]
@YuChern-Intel ， i tried but still met the same issue, below is the snapshot,

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/102842442/67bcbb95-687d-459a-851f-4e40cd0fc22f)

**Comment by alberxualberxu** [comment]
@YuChern-Intel does NB support Win11? My current machine is Win11

**Comment by alberxualberxu** [comment]
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/102842442/4044f8f2-43ab-4d8c-8d6d-0f649a6c4b55)

**Comment by YuChern-Intel** [comment]
OpenVINO™ Notebooks are supported in Windows 11. I am using Windows 11 and Python 3.10.8.

Regarding your latest error (Bad address (C:\projects\libzmq\src\epoll.cpp:100), the issue happened might due to VPN settings. 

Try with the steps below.
1) Run Command Prompt as administrator.
2) Type the command, netsh winsock reset
3) Reboot your computer.

**Comment by alberxualberxu** [comment]
@YuChern-Intel 236 can run by your suggestion, thanks a lot!

**Comment by YuChern-Intel** [comment]
Closing issue as issue has been resolved.
