### ISSUE TITLE
[Notebook Request] Neural Chat 7B

### ISSUE THREAD

**Issue by mahimairaja** [openvinotoolkit/openvino_notebooks#1489]
Hi team!

I find this 7B model - [Neural Chat](https://huggingface.co/Intel/neural-chat-7b-v3-1) from <b> Intel<b> to be outperforming.

It would be a great deal to add it to the awesome repo

Thanks

**Comment by yury-gorbachev** [comment]
Hey!
Totally agree, it is mostly question of time for the team, we have some other notebooks in preparation now.

Is there any chance you could contribute this in our chatbot notebook? It is very straightforward since with OV majority of the things are model independent. As you can see notebook covers 7 models already :)

You can take this PR as example of how this is done: https://github.com/openvinotoolkit/openvino_notebooks/pull/1505

Let us know!
Yury

**Comment by mahimairaja** [comment]
Hi Yury

It seems neural chat just got updated. Will meet back in another PR. Thanks!
