### ISSUE TITLE
[254-llm-chatbot] FP16, int8, and int4 model file sizes are all the same?

### ISSUE THREAD

**Issue by hsulin0806** [openvinotoolkit/openvino_notebooks#1601]
**Describe the bug**
I converted the model in three formats and got the following results, is this correct?
The model is llama-2-7b-chat.

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/33116118/18359d78-047d-4b9a-92a0-81e6e64e6dde)
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/33116118/02329f83-5439-4dd2-99dc-3d8e703e5727)

The following graphics also only display
**The model weights will be quantized to int8.**
is this normal?
Thanks Reply.

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/33116118/bbf1631d-0d0d-41d8-940e-c1d8b7f529ed)
 **Installation instructions (Please mark the checkbox)**
 [✓]  I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks.

**Comment by eaidova** [comment]
@hsulin0806 looks like it is optimum issue that was changed in https://github.com/huggingface/optimum-intel/pull/484 and fixed in https://github.com/huggingface/optimum-intel/pull/495

I recommend to uninstall optimum and optimum intel, remove old models and try one more time with our updated notebook version https://github.com/openvinotoolkit/openvino_notebooks/pull/1622
