### ISSUE TITLE
GPU faster than MULTI:CPU,GPU in 104-model-tools notebook

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/openvino_notebooks#177]
After running a few times, and shutting down the kernel to start fresh on the MULTI benchmark, I keep getting better or equal performance with GPU than MULTI:CPU,GPU when running `resnet-50-pytorch` and `mobilenet-v2-pytorch` models in the 104 notebook. I tried adjusting the duration of the benchmark, but it does not change the result. However, `googlenet-v3` (inceptionv3) MULTI is slightly faster. Anything I should try? 

```
CPU: 11th Gen Intel(R) Core(TM) i7-1185G7E @ 2.80GHz
GPU: Intel(R) Gen12LP HD Graphics (iGPU)
```

mobilenetv2:
![image](https://user-images.githubusercontent.com/15709723/126019211-17ff42c2-0d54-4165-9d39-289e62667f22.png)

resnet-50:
![image](https://user-images.githubusercontent.com/15709723/126019356-8cfb509d-2cd0-4291-aa92-5b1434a33073.png)

inceptionv3:
![image](https://user-images.githubusercontent.com/15709723/126019575-9e42d1cb-7809-40f9-8dea-99e99741918f.png)

**Comment by helena-intel** [comment]
This is why I was hesitant about adding a notebook that shows MULTI without explaining what these settings do and how this works, and when you would use which plugin (GPU, vs MULTI:CPU,GPU vs MULTI:GPU,CPU, vs AUTO). I do not have these answers at the moment. It is also a bit difficult to test because I can only test MULTI/GPU on  my Windows development laptop - so there is quite a bit of variance because of background apps/processes.

15 seconds is probably not enough for a proper benchmark. The first benchmark may also benefit from Turbo Boost, and there is overhead from Jupyter. One reason that I show the benchmark command is to make it easy to copy/paste it in a command line. 

We may want to remove the different benchmark cells that give the impression that this allows you to do a real comparison and add a note about this being an indication of performance - not a proper benchmark of the model.
