### ISSUE TITLE
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...

### ISSUE THREAD

**Issue by Abhijeet241093** [openvinotoolkit/openvino_notebooks#1786]
**Describe the bug**
While custom training using command :
yolo detect train model=yolov8n.pt data=/home/tricubics/Desktop/Automatic_Self_Checkout/automated_self_checkout/self_checkout_ultralytics/data.yaml epochs=100 imgsz=640 project=self_checkout_project device='0,1'

Getting Message 
Transferred 319/355 items from pretrained weights
DDP: debug command /usr/bin/python3 -m torch.distributed.run --nproc_per_node 2 --master_port 48483 /home/tricubics/.config/Ultralytics/DDP/_temp_99pl7w9c139968793272672.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.1.23 🚀 Python-3.8.10 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10001MiB)
                                                           CUDA:1 (NVIDIA GeForce RTX 3080, 10009MiB)
[W Utils.hpp:164] Warning: Environment variable NCCL_BLOCKING_WAIT is deprecated; use TORCH_NCCL_BLOCKING_WAIT instead (function getCvarBool)
[W Utils.hpp:164] Warning: Environment variable NCCL_BLOCKING_WAIT is deprecated; use TORCH_NCCL_BLOCKING_WAIT instead (function getCvarBool)
TensorBoard: Start with 'tensorboard --logdir self_checkout_project/train12', view at http://localhost:6006/
Overriding model.yaml nc=80 with nc=6
Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
**AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...**
Unable to open : http://localhost:6006/

 **Expected behavior**

Program Must run 

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/80f602d9-be07-4f6f-9736-1933c375a98c)

 **Installation instructions (Please mark the checkbox)**
[ Yes  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by riacheruvu** [comment]
Hi @Abhijeet241093, I've seen this issue with the Ultralytics package. This issue is not related to OpenVINO: You may need to confirm your dependencies are all up-to-date, and ensure you're passing the right inputs to the argument. You may have already tried this, but I do recommend reproducing the Ultralytics docs' [YOLOv8 training steps webpage](https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings) as-is, just to confirm your environment setup is correct.

I did notice you raised an issue on the Ultralytics Github, which is the right place to get the resolution! I will request @adrianboguszewski to close this thread, but if there's any issue with the OpenVINO export after training your model, please feel free to re-open the issue.
