### ISSUE TITLE
No module named 'vedastr.utils' in running notebook 208

### ISSUE THREAD

**Issue by zhuo-yoyowz** [openvinotoolkit/openvino_notebooks#255]
When running cell "Download models and convert public model" in notebook 208, there seems to be some download model problems, and also package import problems.  Not sure if it's the connection problems because I'm in China,. 

 
![image](https://user-images.githubusercontent.com/35246475/133715654-89a3c83d-5283-43ac-867a-5d0d65d23f66.png)

**Comment by helena-intel** [comment]
Thanks for reporting this. This is a public model, and model weights for this model are stored on Google Drive. This is sadly not very reliable for these kinds of downloads, and if I understand correctly not available from China.

We are looking into replacing this model with another model that works as well. I would like to use PaddleOCR - but that has a dependency on a different version of OpenCV than openvino-dev requires. I hope we can make that work though. If you have a suggestion for a good OCR model that we can use instead of the current model that would be welcome!

We will also change the notebook so that at least the error message you see when downloading fails is clearer than `No module named 'vedastr.utils'`

**Comment by helena-intel** [comment]
Good news: in the next OpenVINO release (2022.1, release date beginning of March) this model will be downloaded from S3 instead of Google Drive and downloading this model should be more reliable and work in China too.

**Comment by yoyowz** [comment]
> Good news: in the next OpenVINO release (2022.1, release date beginning of March) this model will be downloaded from S3 instead of Google Drive and downloading this model should be more reliable and work in China too.

That's really great news! Thanks, Helena! :)

**Comment by adrianboguszewski** [comment]
@zhuo-yoyowz is it working now?

**Comment by eaidova** [comment]
@zhuo-yoyowz could you please check, the issue still reproducible or not?

**Comment by zhuo-yoyowz** [comment]
> @zhuo-yoyowz could you please check, the issue still reproducible or not?

Hi @eaidova， yes, the issue still exists. I guess it's still due to the failure in downloading the model for "text-recognition-resnet-fc" due to connection issues. 

![image](https://user-images.githubusercontent.com/35246475/208847099-73998005-8dac-4c42-9e50-cd06dc44af32.png)

**Comment by eaidova** [comment]
@zhuo-yoyowz  could you please try to add --num_attempts 5 in omz_downloader parameters?
This parameter responsible for retrying failed downloading

**Comment by zhuo-yoyowz** [comment]
> @zhuo-yoyowz could you please try to add --num_attempts 5 in omz_downloader parameters? This parameter responsible for retrying failed downloading

yes, everything works well now. No more errors in running this notebook. Thanks~

**Comment by eaidova** [comment]
Thank you, probably, we need to include this fix to notebook
