### ISSUE TITLE
Ramp up time with GPU + Auto plugin?

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#541]
Is this the expected behavior for the auto-plugin? It seems that it's hard to predict the latency in the first 30 seconds. 

![image](https://user-images.githubusercontent.com/1720147/164113305-38b5b4fe-cad4-4d7e-8b0d-6102ef51f83a.png)

Environment: Ubuntu 20.04
HW: Intel Gen 12th -- i9-12900H

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/164113654-45720154-1345-4ae5-9fb8-70d393b89678.png)

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/164113712-7f7f0d37-cfaa-40d1-acef-59432cc397e6.png)

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/164113747-b34175ab-9fe2-45f8-ba1b-35bf2565e33c.png)

**Comment by zhuo-yoyowz** [comment]
I've done the test myself, and got the same behavior. After consulting the engineers, yes, it is confirmed that this is the expected behavior that the latency fluctuates in the first 30 seconds. The reason is that during the device switching, CPU is also doing compiling, besides doing inference. Therefore, the compiling time will become longer. So the latency will keep changing in the first 30 seconds.

**Comment by raymondlo84** [comment]
Ar, that's an interesting catch, but also I think we shall talk about how to avoid these huge resource hogging.
