### ISSUE TITLE
trouble with notebook 220-yolov5-accuracy-check-and-quantization

### ISSUE THREAD

**Issue by hazcoper** [openvinotoolkit/openvino_notebooks#714]
I am having trouble running the model with the gpu

i have tried to change the config function, replacing where it says cpu to gpu. But when I run the quantitization pipeline I get the following error

RuntimeError: Failed to create plugin /home/lennie/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/libs/libopenvino_intel_gpu_plugin.so for device GPU
Please, check your environment
[ NOT_FOUND ] Unsupported property key by plugin: CPU_BIND_THREAD

I managed to use the already converted model with gpu but I am not sure how to do it when you are converting a model

**Comment by eaidova** [comment]
@hazcoper quantization process can be run only on CPU, but the result of quantization after it can be run on GPU

**Comment by hazcoper** [comment]
@eaidova i tried doing that by calling the detect.py with the flag "--device 0", which would be the flag to use with a nvidia gpu, however i got the following error:
" "AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)"]"

how would I call this to use the intel iGPU?

**Comment by eaidova** [comment]
@hazcoper  detect.py is part of original yolov5 repository, I'm not sure that it support iGPU, because it is generic code which works with a lot of different frameworks. 
But you can try to modify yolov5 code to use GPU only for openvino.
For that in the same file inside of notebook folder, you need just replace CPU -> GPU
https://github.com/ultralytics/yolov5/blob/v6.1/models/common.py#L335

**Comment by hazcoper** [comment]
@eaidova thanks! 
I changed that to gpu and it worked correctly!
