### ISSUE TITLE
Incorrect results for pix2pix model

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#819]
It looks like the pix2pix model doesn't give me any meaningful results. Whatever I prompt, I get a result that isn't even close to what I asked for. Look at the below:
![Screenshot from 2023-02-08 18-25-10](https://user-images.githubusercontent.com/4547501/217619583-810f6235-0e36-44e4-ae5e-cd27b58f59d2.png)
![Screenshot from 2023-02-08 18-23-34](https://user-images.githubusercontent.com/4547501/217619606-cd15b3a3-f62d-4610-98df-b84bfed6be58.png)
![image](https://user-images.githubusercontent.com/4547501/217620933-d7789a74-8c7c-4191-bee4-3cce627fb82d.png)

I tried different seeds, a number of steps and strengths.
@eaidova Is this expected? It doesn't look like depicted in README.

**Comment by eaidova** [comment]
@adrianboguszewski  do you mean 231 or image2image in 225?
jugging mention of strengths, it is stable diffusion. in image2image feature prompt used as additional detalization of image. It can not replace some particular details because it does not know image semantic,image used only for skping first step with random generation. Probably, problem in prompt what you provide, as it does not know image content, it can not change or turn something. Instead instruction what it should to do, it expects description how final image should looks like e.g.
Turn him to cyborg -> a photo of cyborg.

but your prompt is valid for 231:
![Turn him into chicken](https://user-images.githubusercontent.com/29454499/218001706-2d3dc58f-b9cd-4d57-b094-cc52fd11d0af.png)

**Comment by adrianboguszewski** [comment]
@eaidova Oh yeah, you're right. I mixed up 2 notebooks. I was using 225, thinking that it was 231. When I tried the same prompt with 231, it worked.

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/218235790-d587d6b1-6640-4a85-bb97-707446237a1b.png)
This is nightmare inducing...
