### ISSUE TITLE
230-yolov8-optimization-benchmark_ During app evaluation FPS

### ISSUE THREAD

**Issue by af-doom** [openvinotoolkit/openvino_notebooks#905]
When I use benchmark_ During app evaluation, YOLOv8n can reach 190FPS on my CPU, but when I infer the picture, the test is about 50FPS. At the same time, other YOLOv8 models also have this problem
benchmark：
![2023-03-13 23-18-15 的屏幕截图](https://user-images.githubusercontent.com/91470350/224746073-bda59290-9c48-46f4-82bb-c30b1e208ec5.png)
infer test
![2023-03-13 23-19-30 的屏幕截图](https://user-images.githubusercontent.com/91470350/224746294-30001650-8293-4520-9c80-163f0dbd1ec8.png)

**Comment by brmarkus** [comment]
When looking closer into the `benchmark_app` console messages (if you copy&paste text instead of a screenshot it would be easier to reference the messages) it says:
- "NUM_STREAMS: 5"
- "5 inference requests"
- "Start inference asynchronously"

This sounds like `benchmark_app` triggers 5 inference requests simultaneously using the asynchronous API.

Where your application/notebook is triggering a synchronous, blocking single infer-request - and time-measurement includes drawing the results via `draw_results()`.

**Comment by hbalasu1** [comment]
Hi @af-doom 
Is this issue resolved?

**Comment by hbalasu1** [comment]
I will close this case since we have provided the solution. 
Please feel free to create a new issue if you have any problems.
